/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cjjwpXpMuXk
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import Image from "next/image";

export function Hero() {
  return (
    <section className="relative w-full h-[80vh] min-h-[500px] overflow-hidden mt-28">
      <Image
        alt="Hero Background"
        className="object-cover object-center"
        width="16000"
        height="700"
        src="/hero.webp"
      />
      <div className="absolute inset-0 bg-gradient-to-r from-gray-900/80 to-transparent" />
      <div className="absolute top-1/2 left-10 -translate-y-1/2 max-w-xl space-y-4 sm:left-16 md:left-20 lg:left-24">
        <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl md:text-5xl lg:text-6xl">
          {/* <h1 className="absolute top-8 left-20 text-7xl font-extrabold text-white mb-4 italic p-4"> */}
          <div className="mb-4">lets learn beyond</div>
          <div className="text-[#C60B52] mt-4">the limit</div>
          {/* </h1> */}
        </h1>
        <p className="text-lg text-gray-300 sm:text-xl md:text-2xl">
          Our cutting-edge analytics platform helps you make data-driven decisions that drive your business
          forward.
        </p>
        <div className="flex items-center space-x-4">
          <Button variant="secondary">Learn More</Button>
          <Button variant="default">Get Started</Button>
        </div>
      </div>
    </section>
  );
}
